/****************************************************************************
 * arch/arm/src/gd32e11x/hardware/gd32e113v_pinmap.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_GD32E11X_HARDWARE_GD32E113V_PINMAP_H
#define __ARCH_ARM_SRC_GD32E11X_HARDWARE_GD32E113V_PINMAP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "gd32e11x_gpio.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Alternate Pin Functions
 * The GD32E113V (100-pin LQFP package) pin definitions.
 * Alternative pin selections are provided with a numeric suffix like _1, _2,
 * _3, etc., indicating remap options via AFIO peripheral configuration.
 */

/* General GPIO output */
#define GPIO_PIN0_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_0)
#define GPIO_PIN1_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_1)
#define GPIO_PIN2_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_2)
#define GPIO_PIN3_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_3)
#define GPIO_PIN4_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_4)
#define GPIO_PIN5_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_5)
#define GPIO_PIN6_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_6)
#define GPIO_PIN7_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_7)
#define GPIO_PIN8_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_8)
#define GPIO_PIN9_OUTPUT       (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_9)
#define GPIO_PIN10_OUTPUT      (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_10)
#define GPIO_PIN11_OUTPUT      (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_11)
#define GPIO_PIN12_OUTPUT      (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_12)
#define GPIO_PIN13_OUTPUT      (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_13)
#define GPIO_PIN14_OUTPUT      (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_14)
#define GPIO_PIN15_OUTPUT      (GPIO_CFG_OUTPUT|GPIO_CFG_PIN_15)

/* General GPIO input */
#define GPIO_PIN0_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_0)
#define GPIO_PIN1_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_1)
#define GPIO_PIN2_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_2)
#define GPIO_PIN3_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_3)
#define GPIO_PIN4_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_4)
#define GPIO_PIN5_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_5)
#define GPIO_PIN6_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_6)
#define GPIO_PIN7_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_7)
#define GPIO_PIN8_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_8)
#define GPIO_PIN9_INPUT        (GPIO_CFG_INPUT|GPIO_CFG_PIN_9)
#define GPIO_PIN10_INPUT       (GPIO_CFG_INPUT|GPIO_CFG_PIN_10)
#define GPIO_PIN11_INPUT       (GPIO_CFG_INPUT|GPIO_CFG_PIN_11)
#define GPIO_PIN12_INPUT       (GPIO_CFG_INPUT|GPIO_CFG_PIN_12)
#define GPIO_PIN13_INPUT       (GPIO_CFG_INPUT|GPIO_CFG_PIN_13)
#define GPIO_PIN14_INPUT       (GPIO_CFG_INPUT|GPIO_CFG_PIN_14)
#define GPIO_PIN15_INPUT       (GPIO_CFG_INPUT|GPIO_CFG_PIN_15)

/* ADC - Analog to Digital Converter */

#define GPIO_ADC01_IN0           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_0)
#define GPIO_ADC01_IN1           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_1)
#define GPIO_ADC01_IN2           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_2)
#define GPIO_ADC01_IN3           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_3)
#define GPIO_ADC01_IN4           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_4)
#define GPIO_ADC01_IN5           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_5)
#define GPIO_ADC01_IN6           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_6)
#define GPIO_ADC01_IN7           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_7)
#define GPIO_ADC01_IN8           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_B|GPIO_CFG_PIN_0)
#define GPIO_ADC01_IN9           (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_B|GPIO_CFG_PIN_1)
#define GPIO_ADC01_IN10          (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_C|GPIO_CFG_PIN_0)
#define GPIO_ADC01_IN11          (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_C|GPIO_CFG_PIN_1)
#define GPIO_ADC01_IN12          (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_C|GPIO_CFG_PIN_2)
#define GPIO_ADC01_IN13          (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_C|GPIO_CFG_PIN_3)
#define GPIO_ADC01_IN14          (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_C|GPIO_CFG_PIN_4)
#define GPIO_ADC01_IN15          (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_C|GPIO_CFG_PIN_5)

/* DAC - Digital to Analog Converter */

#define GPIO_DAC_OUT0            (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_4)
#define GPIO_DAC_OUT1            (GPIO_CFG_INPUT|GPIO_CFG_CTL_AIN|GPIO_CFG_PORT_A|GPIO_CFG_PIN_5)

/* I2C - Inter-Integrated Circuit */

/* I2C0 - No remap */

#undef GPIO_I2C0_SCL_1
#undef GPIO_I2C0_SDA_1
#define GPIO_I2C0_SCL_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFOD|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_6)
#define GPIO_I2C0_SDA_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFOD|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_7)
#define GPIO_I2C0_SMBA_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_5)

/* I2C0 - Remap */

#define GPIO_I2C0_SCL_2          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFOD|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_8)
#define GPIO_I2C0_SDA_2          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFOD|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_9)
#define GPIO_I2C0_SMBA_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_5)

/* I2C1 - No remap */

#define GPIO_I2C1_SCL_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFOD|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_10)
#define GPIO_I2C1_SDA_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFOD|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_11)
#define GPIO_I2C1_SMBA_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_SPEED_50MHZ|GPIO_CFG_PORT_B|GPIO_CFG_PIN_12)

/* SPI - Serial Peripheral Interface */

/* SPI0 - No remap */

#define GPIO_SPI0_MISO_1         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_6)
#define GPIO_SPI0_MOSI_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_7)
#define GPIO_SPI0_NSS_1          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_4)
#define GPIO_SPI0_SCK_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_5)

/* SPI0 - Remap */

#define GPIO_SPI0_MISO_2         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_4)
#define GPIO_SPI0_MOSI_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_5)
#define GPIO_SPI0_NSS_2          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_15)
#define GPIO_SPI0_SCK_2          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_3)

/* SPI1 - No remap */

#define GPIO_SPI1_MISO_1         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_14)
#define GPIO_SPI1_MOSI_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_15)
#define GPIO_SPI1_NSS_1          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_12)
#define GPIO_SPI1_SCK_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_13)

/* SPI2 - No remap */

#define GPIO_SPI2_MISO_1         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_4)
#define GPIO_SPI2_MOSI_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_5)
#define GPIO_SPI2_NSS_1          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_15)
#define GPIO_SPI2_SCK_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_3)

/* SPI2 - Remap */

#define GPIO_SPI2_MISO_2         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_C|GPIO_CFG_PIN_11)
#define GPIO_SPI2_MOSI_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_12)
#define GPIO_SPI2_NSS_2          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_4)
#define GPIO_SPI2_SCK_2          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_10)

/* TIMER - Timers */

/* TIMER0 - No remap */

#define GPIO_TIMER0_CH0OUT_1     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_8)
#define GPIO_TIMER0_CH0OUTN_1    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_13)
#define GPIO_TIMER0_CH1OUT_1     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_9)
#define GPIO_TIMER0_CH1OUTN_1    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_14)
#define GPIO_TIMER0_CH2OUT_1     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_10)
#define GPIO_TIMER0_CH2OUTN_1    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_15)
#define GPIO_TIMER0_CH3OUT_1     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_11)
#define GPIO_TIMER0_ETI_1        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_12)
#define GPIO_TIMER0_BRKIN_1      (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_12)

/* TIMER0 - Partial remap */

#define GPIO_TIMER0_CH0OUT_2     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_8)
#define GPIO_TIMER0_CH0OUTN_2    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_7)
#define GPIO_TIMER0_CH1OUT_2     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_9)
#define GPIO_TIMER0_CH1OUTN_2    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_0)
#define GPIO_TIMER0_CH2OUT_2     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_10)
#define GPIO_TIMER0_CH2OUTN_2    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_1)
#define GPIO_TIMER0_CH3OUT_2     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_11)
#define GPIO_TIMER0_ETI_2        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_12)
#define GPIO_TIMER0_BRKIN_2      (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_6)

/* TIMER0 - Full remap */

#define GPIO_TIMER0_CH0OUT_3     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_E|GPIO_CFG_PIN_9)
#define GPIO_TIMER0_CH0OUTN_3    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_E|GPIO_CFG_PIN_8)
#define GPIO_TIMER0_CH1OUT_3     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_E|GPIO_CFG_PIN_11)
#define GPIO_TIMER0_CH1OUTN_3    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_E|GPIO_CFG_PIN_10)
#define GPIO_TIMER0_CH2OUT_3     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_E|GPIO_CFG_PIN_13)
#define GPIO_TIMER0_CH2OUTN_3    (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_E|GPIO_CFG_PIN_12)
#define GPIO_TIMER0_CH3OUT_3     (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_E|GPIO_CFG_PIN_14)
#define GPIO_TIMER0_ETI_3        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_E|GPIO_CFG_PIN_7)
#define GPIO_TIMER0_BRKIN_3      (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_E|GPIO_CFG_PIN_15)

/* TIMER1 - No remap */

#define GPIO_TIMER1_CH0_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_0)
#define GPIO_TIMER1_CH1_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_1)
#define GPIO_TIMER1_CH2_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_2)
#define GPIO_TIMER1_CH3_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_3)
#define GPIO_TIMER1_ETI_1        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_0)

/* TIMER1 - Partial remap 1 */

#define GPIO_TIMER1_CH0_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_15)
#define GPIO_TIMER1_CH1_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_3)
#define GPIO_TIMER1_CH2_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_2)
#define GPIO_TIMER1_CH3_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_3)
#define GPIO_TIMER1_ETI_2        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_15)

/* TIMER1 - Partial remap 2 */

#define GPIO_TIMER1_CH0_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_0)
#define GPIO_TIMER1_CH1_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_1)
#define GPIO_TIMER1_CH2_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_10)
#define GPIO_TIMER1_CH3_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_11)
#define GPIO_TIMER1_ETI_3        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_0)

/* TIMER1 - Full remap */

#define GPIO_TIMER1_CH0_4        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_15)
#define GPIO_TIMER1_CH1_4        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_3)
#define GPIO_TIMER1_CH2_4        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_10)
#define GPIO_TIMER1_CH3_4        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_11)
#define GPIO_TIMER1_ETI_4        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_15)

/* TIMER2 - No remap */

#define GPIO_TIMER2_CH0_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_6)
#define GPIO_TIMER2_CH1_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_7)
#define GPIO_TIMER2_CH2_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_0)
#define GPIO_TIMER2_CH3_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_1)
#define GPIO_TIMER2_ETI_1        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_2)

/* TIMER2 - Partial remap */

#define GPIO_TIMER2_CH0_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_4)
#define GPIO_TIMER2_CH1_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_5)
#define GPIO_TIMER2_CH2_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_0)
#define GPIO_TIMER2_CH3_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_1)
#define GPIO_TIMER2_ETI_2        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_2)

/* TIMER2 - Full remap */

#define GPIO_TIMER2_CH0_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_6)
#define GPIO_TIMER2_CH1_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_7)
#define GPIO_TIMER2_CH2_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_8)
#define GPIO_TIMER2_CH3_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_9)
#define GPIO_TIMER2_ETI_3        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_2)

/* TIMER3 - No remap */

#define GPIO_TIMER3_CH0_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_6)
#define GPIO_TIMER3_CH1_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_7)
#define GPIO_TIMER3_CH2_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_8)
#define GPIO_TIMER3_CH3_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_9)
#define GPIO_TIMER3_ETI_1        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_E|GPIO_CFG_PIN_0)

/* TIMER3 - Remap */

#define GPIO_TIMER3_CH0_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_12)
#define GPIO_TIMER3_CH1_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_13)
#define GPIO_TIMER3_CH2_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_14)
#define GPIO_TIMER3_CH3_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_15)
#define GPIO_TIMER3_ETI_2        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_E|GPIO_CFG_PIN_0)

/* TIMER4 - No remap */

#define GPIO_TIMER4_CH0_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_0)
#define GPIO_TIMER4_CH1_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_1)
#define GPIO_TIMER4_CH2_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_2)
#define GPIO_TIMER4_CH3_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_3)

/* USART/UART - Universal Synchronous/Asynchronous Receiver Transmitter */

/* USART0 - No remap */

#define GPIO_USART0_TX_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_9)
#define GPIO_USART0_RX_1         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_10)
#define GPIO_USART0_CK           (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_8)
#define GPIO_USART0_CTS          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_11)
#define GPIO_USART0_RTS          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_12)

/* USART0 - Remap */

#define GPIO_USART0_TX_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_6)
#define GPIO_USART0_RX_2         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_7)

/* USART1 - No remap */

#define GPIO_USART1_TX_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_2)
#define GPIO_USART1_RX_1         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_3)
#define GPIO_USART1_CK_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_4)
#define GPIO_USART1_CTS_1        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_A|GPIO_CFG_PIN_0)
#define GPIO_USART1_RTS_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_A|GPIO_CFG_PIN_1)

/* USART1 - Remap */

#define GPIO_USART1_TX_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_5)
#define GPIO_USART1_RX_2         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_6)
#define GPIO_USART1_CK_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_7)
#define GPIO_USART1_CTS_2        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_3)
#define GPIO_USART1_RTS_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_4)

/* USART2 - No remap */

#define GPIO_USART2_TX_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_10)
#define GPIO_USART2_RX_1         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_11)
#define GPIO_USART2_CK_1         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_12)
#define GPIO_USART2_CTS_1        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_13)
#define GPIO_USART2_RTS_1        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_14)

/* USART2 - Partial remap */

#define GPIO_USART2_TX_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_10)
#define GPIO_USART2_RX_2         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_C|GPIO_CFG_PIN_11)
#define GPIO_USART2_CK_2         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_12)
#define GPIO_USART2_CTS_2        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_B|GPIO_CFG_PIN_13)
#define GPIO_USART2_RTS_2        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_B|GPIO_CFG_PIN_14)

/* USART2 - Full remap */

#define GPIO_USART2_TX_3         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_8)
#define GPIO_USART2_RX_3         (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_9)
#define GPIO_USART2_CK_3         (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_10)
#define GPIO_USART2_CTS_3        (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_11)
#define GPIO_USART2_RTS_3        (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_D|GPIO_CFG_PIN_12)

/* UART3 - No remap */

#define GPIO_UART3_TX_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_10)
#define GPIO_UART3_RX_1          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_C|GPIO_CFG_PIN_11)

/* UART4 - No remap */

#define GPIO_UART4_TX_1          (GPIO_CFG_OUTPUT|GPIO_CFG_CTL_AFPP|GPIO_CFG_PORT_C|GPIO_CFG_PIN_12)
#define GPIO_UART4_RX_1          (GPIO_CFG_INPUT|GPIO_CFG_CTL_INFLOAT|GPIO_CFG_PORT_D|GPIO_CFG_PIN_2)

#endif /* __ARCH_ARM_SRC_GD32E11X_HARDWARE_GD32E113V_PINMAP_H */

