/****************************************************************************
 * arch/arm/src/gd32e11x/hardware/gd32e113v_pinmap.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_GD32E11X_HARDWARE_GD32E113V_PINMAP_H
#define __ARCH_ARM_SRC_GD32E11X_HARDWARE_GD32E113V_PINMAP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "../gd32e11x_gpio.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Alternate Pin Functions
 * The GD32E113V (100-pin LQFP package) pin definitions.
 * Alternative pin selections are provided with a numeric suffix like _0, _1,
 * _2, etc., indicating remap options via AFIO peripheral configuration.
 */

/* ADC - Analog to Digital Converter */

#define GPIO_ADC01_IN0           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN0)
#define GPIO_ADC01_IN1           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN1)
#define GPIO_ADC01_IN2           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN2)
#define GPIO_ADC01_IN3           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN3)
#define GPIO_ADC01_IN4           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN4)
#define GPIO_ADC01_IN5           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN5)
#define GPIO_ADC01_IN6           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN6)
#define GPIO_ADC01_IN7           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN7)
#define GPIO_ADC01_IN8           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN0)
#define GPIO_ADC01_IN9           (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN1)
#define GPIO_ADC01_IN10          (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN0)
#define GPIO_ADC01_IN11          (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN1)
#define GPIO_ADC01_IN12          (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN2)
#define GPIO_ADC01_IN13          (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN3)
#define GPIO_ADC01_IN14          (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN4)
#define GPIO_ADC01_IN15          (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN5)

/* CAN - Controller Area Network */

/* CAN0 - No remap */

#define GPIO_CAN0_RX_0           (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN11)
#define GPIO_CAN0_TX_0           (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN12)

/* CAN0 - Partial remap */

#define GPIO_CAN0_RX_1           (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN8)
#define GPIO_CAN0_TX_1           (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN9)

/* CAN0 - Full remap */

#define GPIO_CAN0_RX_2           (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN0)
#define GPIO_CAN0_TX_2           (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN1)

/* DAC - Digital to Analog Converter */

#define GPIO_DAC_OUT0            (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN4)
#define GPIO_DAC_OUT1            (GPIO_INPUT|GPIO_CNF_ANALOGIN|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN5)

/* I2C - Inter-Integrated Circuit */

/* I2C0 - No remap */

#define GPIO_I2C0_SCL_0          (GPIO_ALT|GPIO_CNF_AFOD|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN6)
#define GPIO_I2C0_SDA_0          (GPIO_ALT|GPIO_CNF_AFOD|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN7)
#define GPIO_I2C0_SMBA_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN5)

/* I2C0 - Remap */

#define GPIO_I2C0_SCL_1          (GPIO_ALT|GPIO_CNF_AFOD|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN8)
#define GPIO_I2C0_SDA_1          (GPIO_ALT|GPIO_CNF_AFOD|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN9)
#define GPIO_I2C0_SMBA_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN5)

/* I2C1 - No remap */

#define GPIO_I2C1_SCL_0          (GPIO_ALT|GPIO_CNF_AFOD|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN10)
#define GPIO_I2C1_SDA_0          (GPIO_ALT|GPIO_CNF_AFOD|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN11)
#define GPIO_I2C1_SMBA_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN12)

/* SPI - Serial Peripheral Interface */

/* SPI0 - No remap */

#define GPIO_SPI0_MISO_0         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN6)
#define GPIO_SPI0_MOSI_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN7)
#define GPIO_SPI0_NSS_0          (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN4)
#define GPIO_SPI0_SCK_0          (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN5)

/* SPI0 - Remap */

#define GPIO_SPI0_MISO_1         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN4)
#define GPIO_SPI0_MOSI_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN5)
#define GPIO_SPI0_NSS_1          (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN15)
#define GPIO_SPI0_SCK_1          (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN3)

/* SPI1 - No remap */

#define GPIO_SPI1_MISO_0         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN14)
#define GPIO_SPI1_MOSI_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN15)
#define GPIO_SPI1_NSS_0          (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN12)
#define GPIO_SPI1_SCK_0          (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN13)

/* SPI2 - No remap */

#define GPIO_SPI2_MISO_0         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN4)
#define GPIO_SPI2_MOSI_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN5)
#define GPIO_SPI2_NSS_0          (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN15)
#define GPIO_SPI2_SCK_0          (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN3)

/* SPI2 - Remap */

#define GPIO_SPI2_MISO_1         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN11)
#define GPIO_SPI2_MOSI_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN12)
#define GPIO_SPI2_NSS_1          (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN4)
#define GPIO_SPI2_SCK_1          (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN10)

/* TIMER - Timers */

/* TIMER0 - No remap */

#define GPIO_TIMER0_CH0OUT_0     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN8)
#define GPIO_TIMER0_CH0OUTN_0    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN13)
#define GPIO_TIMER0_CH1OUT_0     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN9)
#define GPIO_TIMER0_CH1OUTN_0    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN14)
#define GPIO_TIMER0_CH2OUT_0     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN10)
#define GPIO_TIMER0_CH2OUTN_0    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN15)
#define GPIO_TIMER0_CH3OUT_0     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN11)
#define GPIO_TIMER0_ETI_0        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN12)
#define GPIO_TIMER0_BRKIN_0      (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN12)

/* TIMER0 - Partial remap */

#define GPIO_TIMER0_CH0OUT_1     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN8)
#define GPIO_TIMER0_CH0OUTN_1    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN7)
#define GPIO_TIMER0_CH1OUT_1     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN9)
#define GPIO_TIMER0_CH1OUTN_1    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN0)
#define GPIO_TIMER0_CH2OUT_1     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN10)
#define GPIO_TIMER0_CH2OUTN_1    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN1)
#define GPIO_TIMER0_CH3OUT_1     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN11)
#define GPIO_TIMER0_ETI_1        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN12)
#define GPIO_TIMER0_BRKIN_1      (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN6)

/* TIMER0 - Full remap */

#define GPIO_TIMER0_CH0OUT_2     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTE|GPIO_PIN9)
#define GPIO_TIMER0_CH0OUTN_2    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTE|GPIO_PIN8)
#define GPIO_TIMER0_CH1OUT_2     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTE|GPIO_PIN11)
#define GPIO_TIMER0_CH1OUTN_2    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTE|GPIO_PIN10)
#define GPIO_TIMER0_CH2OUT_2     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTE|GPIO_PIN13)
#define GPIO_TIMER0_CH2OUTN_2    (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTE|GPIO_PIN12)
#define GPIO_TIMER0_CH3OUT_2     (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTE|GPIO_PIN14)
#define GPIO_TIMER0_ETI_2        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTE|GPIO_PIN7)
#define GPIO_TIMER0_BRKIN_2      (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTE|GPIO_PIN15)

/* TIMER1 - No remap */

#define GPIO_TIMER1_CH0_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN0)
#define GPIO_TIMER1_CH1_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN1)
#define GPIO_TIMER1_CH2_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN2)
#define GPIO_TIMER1_CH3_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN3)
#define GPIO_TIMER1_ETI_0        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN0)

/* TIMER1 - Partial remap 1 */

#define GPIO_TIMER1_CH0_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN15)
#define GPIO_TIMER1_CH1_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN3)
#define GPIO_TIMER1_CH2_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN2)
#define GPIO_TIMER1_CH3_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN3)
#define GPIO_TIMER1_ETI_1        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN15)

/* TIMER1 - Partial remap 2 */

#define GPIO_TIMER1_CH0_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN0)
#define GPIO_TIMER1_CH1_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN1)
#define GPIO_TIMER1_CH2_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN10)
#define GPIO_TIMER1_CH3_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN11)
#define GPIO_TIMER1_ETI_2        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN0)

/* TIMER1 - Full remap */

#define GPIO_TIMER1_CH0_3        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN15)
#define GPIO_TIMER1_CH1_3        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN3)
#define GPIO_TIMER1_CH2_3        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN10)
#define GPIO_TIMER1_CH3_3        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN11)
#define GPIO_TIMER1_ETI_3        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN15)

/* TIMER2 - No remap */

#define GPIO_TIMER2_CH0_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN6)
#define GPIO_TIMER2_CH1_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN7)
#define GPIO_TIMER2_CH2_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN0)
#define GPIO_TIMER2_CH3_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN1)
#define GPIO_TIMER2_ETI_0        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN2)

/* TIMER2 - Partial remap */

#define GPIO_TIMER2_CH0_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN4)
#define GPIO_TIMER2_CH1_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN5)
#define GPIO_TIMER2_CH2_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN0)
#define GPIO_TIMER2_CH3_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN1)
#define GPIO_TIMER2_ETI_1        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN2)

/* TIMER2 - Full remap */

#define GPIO_TIMER2_CH0_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN6)
#define GPIO_TIMER2_CH1_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN7)
#define GPIO_TIMER2_CH2_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN8)
#define GPIO_TIMER2_CH3_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN9)
#define GPIO_TIMER2_ETI_2        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN2)

/* TIMER3 - No remap */

#define GPIO_TIMER3_CH0_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN6)
#define GPIO_TIMER3_CH1_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN7)
#define GPIO_TIMER3_CH2_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN8)
#define GPIO_TIMER3_CH3_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN9)
#define GPIO_TIMER3_ETI_0        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTE|GPIO_PIN0)

/* TIMER3 - Remap */

#define GPIO_TIMER3_CH0_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN12)
#define GPIO_TIMER3_CH1_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN13)
#define GPIO_TIMER3_CH2_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN14)
#define GPIO_TIMER3_CH3_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN15)
#define GPIO_TIMER3_ETI_1        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTE|GPIO_PIN0)

/* TIMER4 - No remap */

#define GPIO_TIMER4_CH0_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN0)
#define GPIO_TIMER4_CH1_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN1)
#define GPIO_TIMER4_CH2_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN2)
#define GPIO_TIMER4_CH3_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN3)

/* USART/UART - Universal Synchronous/Asynchronous Receiver Transmitter */

/* USART0 - No remap */

#define GPIO_USART0_TX_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN9)
#define GPIO_USART0_RX_0         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN10)
#define GPIO_USART0_CK_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN8)
#define GPIO_USART0_CTS_0        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN11)
#define GPIO_USART0_RTS_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN12)

/* USART0 - Remap */

#define GPIO_USART0_TX_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN6)
#define GPIO_USART0_RX_1         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN7)
#define GPIO_USART0_CK_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN8)
#define GPIO_USART0_CTS_1        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN11)
#define GPIO_USART0_RTS_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN12)

/* USART1 - No remap */

#define GPIO_USART1_TX_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN2)
#define GPIO_USART1_RX_0         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN3)
#define GPIO_USART1_CK_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN4)
#define GPIO_USART1_CTS_0        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTA|GPIO_PIN0)
#define GPIO_USART1_RTS_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTA|GPIO_PIN1)

/* USART1 - Remap */

#define GPIO_USART1_TX_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN5)
#define GPIO_USART1_RX_1         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN6)
#define GPIO_USART1_CK_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN7)
#define GPIO_USART1_CTS_1        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN3)
#define GPIO_USART1_RTS_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN4)

/* USART2 - No remap */

#define GPIO_USART2_TX_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN10)
#define GPIO_USART2_RX_0         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN11)
#define GPIO_USART2_CK_0         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN12)
#define GPIO_USART2_CTS_0        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN13)
#define GPIO_USART2_RTS_0        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN14)

/* USART2 - Partial remap */

#define GPIO_USART2_TX_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN10)
#define GPIO_USART2_RX_1         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN11)
#define GPIO_USART2_CK_1         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN12)
#define GPIO_USART2_CTS_1        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTB|GPIO_PIN13)
#define GPIO_USART2_RTS_1        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTB|GPIO_PIN14)

/* USART2 - Full remap */

#define GPIO_USART2_TX_2         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN8)
#define GPIO_USART2_RX_2         (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN9)
#define GPIO_USART2_CK_2         (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN10)
#define GPIO_USART2_CTS_2        (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN11)
#define GPIO_USART2_RTS_2        (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTD|GPIO_PIN12)

/* UART3 - No remap */

#define GPIO_UART3_TX_0          (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN10)
#define GPIO_UART3_RX_0          (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN11)

/* UART4 - No remap */

#define GPIO_UART4_TX_0          (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHZ|GPIO_PORTC|GPIO_PIN12)
#define GPIO_UART4_RX_0          (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN2)

#endif /* __ARCH_ARM_SRC_GD32E11X_HARDWARE_GD32E113V_PINMAP_H */
